In [7]:
from tsfresh import extract_features, extract_relevant_features, select_features
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.feature_extraction import ComprehensiveFCParameters

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd

y_train_holed = pd.read_csv("data/processed/y_train_holed.csv")
y_train_complete = pd.read_csv("data/processed/y_train_complete.csv")

In [16]:
X = y_train_complete.iloc[:,:2]
X.insert(0, 'id', 0)
y = y_train_complete.iloc[:,1:2]
y.insert(0, 'id', 0)
y

      id  holed_1
0      0    578.0
1      0    533.0
2      0    623.0
3      0    613.0
4      0   1823.0
...   ..      ...
1052   0    576.0
1053   0    514.0
1054   0    607.0
1055   0    665.0
1056   0    677.0

[1057 rows x 2 columns]

In [18]:
extracted_features = extract_features(X, column_id="id", column_sort="Horodate")
extracted_features

Feature Extraction: 100%|██████████| 1/1 [00:12<00:00, 12.48s/it]

,holed_1__variance_larger_than_standard_deviation,holed_1__has_duplicate_max,holed_1__has_duplicate_min,holed_1__has_duplicate,holed_1__sum_values,holed_1__abs_energy,holed_1__mean_abs_change,holed_1__mean_change,holed_1__mean_second_derivative_central,holed_1__median,...,holed_1__fourier_entropy__bins_5,holed_1__fourier_entropy__bins_10,holed_1__fourier_entropy__bins_100,holed_1__permutation_entropy__dimension_3__tau_1,holed_1__permutation_entropy__dimension_4__tau_1,holed_1__permutation_entropy__dimension_5__tau_1,holed_1__permutation_entropy__dimension_6__tau_1,holed_1__permutation_entropy__dimension_7__tau_1,holed_1__query_similarity_count__query_None__threshold_0.0,holed_1__mean_n_absolute_max__number_of_maxima_7
0,1.0,0.0,1.0,1.0,897585.0,940941189.0,293.019886,0.09375,0.027014,789.0,...,0.432434,0.859793,2.966393,1.774633,3.126491,4.644973,6.035552,6.728018,NaN,2634.0